Parameters:
  UbuntuAMI:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2
    Description: EC2 Instance Ubuntu AMI

Resources:
  HardK8sWorker0:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !ImportValue hard-k8s-subnet
      SecurityGroupIds:
      - !ImportValue hard-k8s-sg
      ImageId: !Ref UbuntuAMI
      KeyName: !Ref ParamKeyName
      PrivateIpAddress: 10.240.0.20
      # SourceDestCheck: false
      UserData:
        Fn::Base64: |-
          Content-Type: multipart/mixed; boundary="//"
          MIME-Version: 1.0
          
          --//
          Content-Type: text/cloud-config; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="cloud-config.txt"
          
          #cloud-config
          fqdn: worker-0.k8shardway.local
          hostname: worker-0
          runcmd:
            - echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
          write_files:
            - path: /etc/hosts
              permissions: '0644'
              content: |
                127.0.0.1   localhost localhost.localdomain
                # Kubernetes the Hard Way - hostnames
                10.240.0.10 master-0
                10.240.0.11 master-1
                10.240.0.12 master-2
                10.240.0.20 worker-0
                10.240.0.21 worker-1
                10.240.0.22 worker-2
          
          --//
          Content-Type: text/x-shellscript; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="userdata.txt"
          
          #!/bin/bash
          echo 10.200.0.0/24 > /opt/pod_cidr.txt
          --//
      Tags: [ { "Key": "Name", "Value": "worker-0" } ]

  HardK8sWorker1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !ImportValue hard-k8s-subnet
      SecurityGroupIds:
      - !ImportValue hard-k8s-sg
      ImageId: !Ref UbuntuAMI
      KeyName: !Ref ParamKeyName
      PrivateIpAddress: 10.240.0.21
      # SourceDestCheck: false
      UserData:
        Fn::Base64: |-
          Content-Type: multipart/mixed; boundary="//"
          MIME-Version: 1.0
          
          --//
          Content-Type: text/cloud-config; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="cloud-config.txt"
          
          #cloud-config
          fqdn: worker-1.k8shardway.local
          hostname: worker-1
          runcmd:
            - echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
          write_files:
            - path: /etc/hosts
              permissions: '0644'
              content: |
                127.0.0.1   localhost localhost.localdomain
                # Kubernetes the Hard Way - hostnames
                10.240.0.10 master-0
                10.240.0.11 master-1
                10.240.0.12 master-2
                10.240.0.20 worker-0
                10.240.0.21 worker-1
                10.240.0.22 worker-2
          
          --//
          Content-Type: text/x-shellscript; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="userdata.txt"
          
          #!/bin/bash
          echo 10.200.1.0/24 > /opt/pod_cidr.txt
          --//
      Tags: [ { "Key": "Name", "Value": "worker-1" } ]

  HardK8sWorker2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !ImportValue hard-k8s-subnet
      SecurityGroupIds:
      - !ImportValue hard-k8s-sg
      ImageId: !Ref UbuntuAMI
      KeyName: !Ref ParamKeyName
      PrivateIpAddress: 10.240.0.22
      # SourceDestCheck: false
      UserData:
        Fn::Base64: |-
          Content-Type: multipart/mixed; boundary="//"
          MIME-Version: 1.0
          
          --//
          Content-Type: text/cloud-config; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="cloud-config.txt"
          
          #cloud-config
          fqdn: worker-2.k8shardway.local
          hostname: worker-2
          runcmd:
            - echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
          write_files:
            - path: /etc/hosts
              permissions: '0644'
              content: |
                127.0.0.1   localhost localhost.localdomain
                # Kubernetes the Hard Way - hostnames
                10.240.0.10 master-0
                10.240.0.11 master-1
                10.240.0.12 master-2
                10.240.0.20 worker-0
                10.240.0.21 worker-1
                10.240.0.22 worker-2
          
          --//
          Content-Type: text/x-shellscript; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="userdata.txt"
          
          #!/bin/bash
          echo 10.200.2.0/24 > /opt/pod_cidr.txt
          --//
      Tags: [ { "Key": "Name", "Value": "worker-2" } ]

Parameters:
  ParamKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: ec2-key

Outputs:
  Worker0:
    Value: !Ref HardK8sWorker0
    Export: { Name: hard-k8s-worker-0 }
  Worker1:
    Value: !Ref HardK8sWorker1
    Export: { Name: hard-k8s-worker-1 }
  Worker2:
    Value: !Ref HardK8sWorker2
    Export: { Name: hard-k8s-worker-2 }