Parameters:
  UbuntuAMI:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
    Description: EC2 Instance Ubuntu AMI
  ParamKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: ec2-key

Resources:
  HardK8sMaster0:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !ImportValue hard-k8s-subnet
      SecurityGroupIds:
      - !ImportValue hard-k8s-sg
      ImageId: !Ref UbuntuAMI
      KeyName: !Ref ParamKeyName
      PrivateIpAddress: 10.240.0.10
      # SourceDestCheck: false
      UserData:
        Fn::Base64: |-
          #cloud-config
          fqdn: master-0.k8shardway.local
          hostname: master-0
          runcmd:
            - echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
          write_files:
            - path: /etc/hosts
              permissions: '0644'
              content: |
                127.0.0.1   localhost localhost.localdomain
                # Kubernetes the Hard Way - hostnames
                10.240.0.10 master-0
                10.240.0.11 master-1
                10.240.0.12 master-2
                10.240.0.20 worker-0
                10.240.0.21 worker-1
                10.240.0.22 worker-2
      Tags: [ { "Key": "Name", "Value": "master-0" } ]

  HardK8sMaster1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !ImportValue hard-k8s-subnet
      SecurityGroupIds:
      - !ImportValue hard-k8s-sg
      ImageId: !Ref UbuntuAMI
      KeyName: !Ref ParamKeyName
      PrivateIpAddress: 10.240.0.11
      # SourceDestCheck: false
      UserData:
        Fn::Base64: |-
          #cloud-config
          fqdn: master-1.k8shardway.local
          hostname: master-1
          runcmd:
            - echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
          write_files:
            - path: /etc/hosts
              permissions: '0644'
              content: |
                127.0.0.1   localhost localhost.localdomain
                # Kubernetes the Hard Way - hostnames
                10.240.0.10 master-0
                10.240.0.11 master-1
                10.240.0.12 master-2
                10.240.0.20 worker-0
                10.240.0.21 worker-1
                10.240.0.22 worker-2
      Tags: [ { "Key": "Name", "Value": "master-1" } ]

  HardK8sMaster2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !ImportValue hard-k8s-subnet
      SecurityGroupIds:
      - !ImportValue hard-k8s-sg
      ImageId: !Ref UbuntuAMI
      KeyName: !Ref ParamKeyName
      PrivateIpAddress: 10.240.0.12
      # SourceDestCheck: false
      UserData:
        Fn::Base64: |-
          #cloud-config
          fqdn: master-2.k8shardway.local
          hostname: master-2
          runcmd:
            - echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
          write_files:
            - path: /etc/hosts
              permissions: '0644'
              content: |
                127.0.0.1   localhost localhost.localdomain
                # Kubernetes the Hard Way - hostnames
                10.240.0.10 master-0
                10.240.0.11 master-1
                10.240.0.12 master-2
                10.240.0.20 worker-0
                10.240.0.21 worker-1
                10.240.0.22 worker-2
      Tags: [ { "Key": "Name", "Value": "master-2" } ]

Outputs:
  Master0:
    Value: !Ref HardK8sMaster0
    Export: { Name: hard-k8s-master-0 }
  Master1:
    Value: !Ref HardK8sMaster1
    Export: { Name: hard-k8s-master-1 }
  Master2:
    Value: !Ref HardK8sMaster2
    Export: { Name: hard-k8s-master-2 }
